/**
 * Shared Browser Connector ↔ Capture Bridge protocol (V1).
 *
 * This file is intentionally framework-agnostic and is used by:
 * - the Chromium MV3 extension (extraction → POST body),
 * - the Obsidian plugin (Capture Bridge request validation + result mapping).
 *
 * It carries only the allowlisted Web Capture evidence. It must never
 * accept paths, commands, vault destinations, HTML, cookies, tags, or
 * arbitrary CLI arguments.
 */

export const WEB_CAPTURE_SCHEMA_VERSION = 1 as const;
export const CAPTURE_PORT = 27124 as const;
export const CAPTURE_BIND_ADDRESS = "127.0.0.1" as const;
export const CAPTURE_ROUTE = "/v1/capture" as const;
export const CAPTURE_URL: string = `http://${CAPTURE_BIND_ADDRESS}:${CAPTURE_PORT}${CAPTURE_ROUTE}`;
/** Required non-simple custom header. Not a secret; it gates mutation. */
export const CONNECTOR_VERSION_HEADER = "X-Paper-Notes-Connector-Version" as const;
export const CONNECTOR_VERSION = "1" as const;
/** Body cap documented in the plan: no larger than 256 KiB. */
export const MAX_CAPTURE_BODY_BYTES = 262144 as const;
/** Hard per-value cap so a malicious page cannot exhaust the bridge. */
export const MAX_CAPTURE_STRING_LENGTH = 20000 as const;
export const MAX_CAPTURE_RECORDS = 16 as const;
export const MAX_CAPTURE_AUTHORS = 200 as const;
export const MAX_CAPTURE_ISSNS = 20 as const;

export const WEB_CAPTURE_SOURCES = [
  "highwire",
  "json_ld",
  "dublin_core",
  "open_graph",
  "doi_scan",
] as const;
export type WebCaptureSource = (typeof WEB_CAPTURE_SOURCES)[number];

export const CAPTURED_BIBLIOGRAPHY_FIELDS = [
  "item_type",
  "title",
  "authors",
  "journal",
  "journal_abbreviation",
  "publication_date",
  "year",
  "volume",
  "issue",
  "pages",
  "doi",
  "pmid",
  "pmcid",
  "arxiv",
  "url",
  "issn",
  "language",
  "abstract",
] as const;
export type CapturedBibliographyField = (typeof CAPTURED_BIBLIOGRAPHY_FIELDS)[number];

export interface CapturedAuthor {
  family?: string;
  given?: string;
  literal?: string;
}

/**
 * The allowlisted bibliographic facts extracted from one supported paper
 * page. Every field is optional because a page may only expose a subset;
 * the core decides completeness and trust.
 */
export type CapturedBibliography = Partial<{
  item_type: "article-journal" | "preprint";
  title: string;
  authors: CapturedAuthor[];
  journal: string;
  journal_abbreviation: string;
  publication_date: string;
  year: number;
  volume: string;
  issue: string;
  pages: string;
  doi: string;
  pmid: string;
  pmcid: string;
  arxiv: string;
  url: string;
  issn: string[];
  language: string;
  abstract: string;
}>;

export interface WebCaptureRecord {
  source: WebCaptureSource;
  values: CapturedBibliography;
}

export interface WebCaptureRequest {
  schema_version: typeof WEB_CAPTURE_SCHEMA_VERSION;
  /** UUID idempotency key generated by the extension for each click. */
  capture_id: string;
  /** Current HTTPS page URL. Never a vault path or local file. */
  page_url: string;
  /** Preserved source records; conflicts are not flattened away. */
  records: WebCaptureRecord[];
}

const SOURCE_SET = new Set<string>(WEB_CAPTURE_SOURCES);
const FIELD_SET = new Set<string>(CAPTURED_BIBLIOGRAPHY_FIELDS);
const ITEM_TYPES = new Set<string>(["article-journal", "preprint"]);

const URL_RE = /^https:\/\//i;
const DATE_RE = /^\d{4}(-\d{2}(-\d{2})?)?$/;
const YEAR_RE = /^\d{4}$/;
const LANGUAGE_RE = /^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})?$/;

const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

function isLeapYear(year: number): boolean {
  return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
}

function isValidCaptureDate(value: string): boolean {
  if (!DATE_RE.test(value)) {
    return false;
  }
  const [yearText, monthText, dayText] = value.split("-");
  const year = Number(yearText);
  if (year < 1000 || year > 9999) {
    return false;
  }
  if (monthText !== undefined) {
    const month = Number(monthText);
    if (month < 1 || month > 12) {
      return false;
    }
    if (dayText !== undefined) {
      const day = Number(dayText);
      const max = month === 2 && isLeapYear(year) ? 29 : DAYS_IN_MONTH[month - 1];
      if (day < 1 || day > max) {
        return false;
      }
    }
  }
  return true;
}

function isRecordObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function isBoundedString(value: unknown, max = MAX_CAPTURE_STRING_LENGTH): value is string {
  return typeof value === "string" && value.length <= max;
}

function isCapturedAuthor(value: unknown): value is CapturedAuthor {
  if (!isRecordObject(value)) {
    return false;
  }
  const keys = Object.keys(value);
  if (keys.length === 0 || keys.some((key) => !["family", "given", "literal"].includes(key))) {
    return false;
  }
  for (const key of ["family", "given", "literal"] as const) {
    const field = value[key];
    if (field !== undefined && !isBoundedString(field)) {
      return false;
    }
  }
  return typeof value.family === "string" || typeof value.literal === "string";
}

function isCapturedBibliography(value: unknown): value is CapturedBibliography {
  if (!isRecordObject(value)) {
    return false;
  }
  const keys = Object.keys(value);
  if (keys.some((key) => !FIELD_SET.has(key))) {
    return false;
  }
  for (const key of keys) {
    const fieldValue = value[key];
    switch (key) {
      case "item_type":
        if (typeof fieldValue !== "string" || !ITEM_TYPES.has(fieldValue)) {
          return false;
        }
        break;
      case "title":
      case "journal":
      case "journal_abbreviation":
      case "publication_date":
      case "volume":
      case "issue":
      case "pages":
      case "doi":
      case "pmid":
      case "pmcid":
      case "arxiv":
      case "url":
      case "language":
      case "abstract":
        if (!isBoundedString(fieldValue)) {
          return false;
        }
        if (key === "publication_date" && !isValidCaptureDate(fieldValue as string)) {
          return false;
        }
        if (key === "language" && !LANGUAGE_RE.test(fieldValue as string)) {
          return false;
        }
        if ((key === "doi" || key === "pmid" || key === "pmcid" || key === "arxiv") && !isNonEmptyString(fieldValue)) {
          return false;
        }
        if (key === "url" && !URL_RE.test(fieldValue as string)) {
          return false;
        }
        break;
      case "year":
        if (typeof fieldValue !== "number" || !Number.isInteger(fieldValue)) {
          return false;
        }
        if (fieldValue < 1000 || fieldValue > 9999 || !YEAR_RE.test(String(fieldValue))) {
          return false;
        }
        break;
      case "authors":
        if (
          !Array.isArray(fieldValue) ||
          fieldValue.length === 0 ||
          fieldValue.length > MAX_CAPTURE_AUTHORS ||
          !fieldValue.every(isCapturedAuthor)
        ) {
          return false;
        }
        break;
      case "issn":
        if (
          !Array.isArray(fieldValue) ||
          fieldValue.length === 0 ||
          fieldValue.length > MAX_CAPTURE_ISSNS ||
          !fieldValue.every((item) => isBoundedString(item) && item.length > 0)
        ) {
          return false;
        }
        break;
      default:
        return false;
    }
  }
  return true;
}

function isWebCaptureRecord(value: unknown): value is WebCaptureRecord {
  if (!isRecordObject(value)) {
    return false;
  }
  const keys = Object.keys(value);
  if (keys.length !== 2 || !keys.includes("source") || !keys.includes("values")) {
    return false;
  }
  if (typeof value.source !== "string" || !SOURCE_SET.has(value.source)) {
    return false;
  }
  return isCapturedBibliography(value.values);
}

/**
 * Strict protocol guard. Returns a human-safe rejection reason when the
 * value is not a valid Web Capture request, or `null` when it is valid.
 */
export function webCaptureRejectionReason(value: unknown): string | null {
  if (!isRecordObject(value)) {
    return "request must be a JSON object";
  }
  const keys = Object.keys(value);
  const allowed = new Set(["schema_version", "capture_id", "page_url", "records"]);
  if (keys.some((key) => !allowed.has(key))) {
    return "request contains unknown fields";
  }
  if (value.schema_version !== WEB_CAPTURE_SCHEMA_VERSION) {
    return "unsupported schema_version";
  }
  if (!isNonEmptyString(value.capture_id) || value.capture_id.length > 128) {
    return "capture_id must be a non-empty string";
  }
  if (!isBoundedString(value.page_url) || !URL_RE.test(value.page_url)) {
    return "page_url must be an HTTPS URL";
  }
  if (
    !Array.isArray(value.records) ||
    value.records.length === 0 ||
    value.records.length > MAX_CAPTURE_RECORDS
  ) {
    return "records must be a non-empty array";
  }
  if (!value.records.every(isWebCaptureRecord)) {
    return "records contain unknown or malformed evidence";
  }
  return null;
}

export function isWebCaptureRequest(value: unknown): value is WebCaptureRequest {
  return webCaptureRejectionReason(value) === null;
}

/**
 * Closed result union sent back from the bridge/plugin to the popup.
 * `unavailable` is produced by the extension itself when the bridge
 * cannot be reached.
 */
export type BrowserCaptureResult =
  | {
      status: "created";
      citationKey: string;
      title: string;
      path: string;
    }
  | {
      status: "existing";
      citationKey: string;
      title: string;
      action: "open";
    }
  | {
      status: "needs_review";
      reviewId: string;
      reason: string;
    }
  | {
      status: "rejected";
      code: string;
      reason: string;
    }
  | {
      status: "unavailable";
      reason: string;
    };

export function isBrowserCaptureResult(value: unknown): value is BrowserCaptureResult {
  if (!isRecordObject(value)) {
    return false;
  }
  switch (value.status) {
    case "created":
      return (
        isNonEmptyString(value.citationKey) &&
        isNonEmptyString(value.title) &&
        isNonEmptyString(value.path)
      );
    case "existing":
      return (
        isNonEmptyString(value.citationKey) &&
        isNonEmptyString(value.title) &&
        value.action === "open"
      );
    case "needs_review":
      return isNonEmptyString(value.reviewId) && isNonEmptyString(value.reason);
    case "rejected":
      return isNonEmptyString(value.code) && isNonEmptyString(value.reason);
    case "unavailable":
      return isNonEmptyString(value.reason);
    default:
      return false;
  }
}

/** All status names, used by exhaustive-result tests. */
export const BROWSER_CAPTURE_RESULT_STATUSES = [
  "created",
  "existing",
  "needs_review",
  "rejected",
  "unavailable",
] as const;
export type BrowserCaptureResultStatus = (typeof BROWSER_CAPTURE_RESULT_STATUSES)[number];
